import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Box3} from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {importedPedestrian,posePedestrian} from '../street-models.js';
const bytes=readFileSync(new URL('../../public/assets/characters/quaternius/casual.glb',import.meta.url));
const gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const npc=importedPedestrian(gltf),box=new Box3().setFromObject(npc);
assert.ok(Math.abs(box.max.y-box.min.y-1.75)<.001);
assert.ok(Math.abs(box.min.y)<.001);
const bones=[];npc.traverse(n=>{if(n.isBone)bones.push(n);});
const before=bones.map(n=>n.quaternion.clone());
for(let i=0;i<30;i++)posePedestrian(npc,1.4/60,1/60);
assert.equal(npc.userData.importedNPC.current.getClip().name,'CharacterArmature|Walk');
assert.ok(bones.some((n,i)=>n.quaternion.angleTo(before[i])>.1),'walking must actually move bones');
for(let i=0;i<30;i++)posePedestrian(npc,3.5/60,1/60);
assert.equal(npc.userData.importedNPC.current.getClip().name,'CharacterArmature|Run');
for(let i=0;i<60;i++)posePedestrian(npc,0,1/60);
assert.equal(npc.userData.importedNPC.current.getClip().name,'CharacterArmature|Idle_Neutral');
assert.ok(bones.every(n=>n.matrix.elements.every(Number.isFinite)));
console.log('Online NPC: loaded real asset, grounded at 1.75 m, animated walk/run/idle.');
