import * as T from 'three';
import {STOPS,LENGTH,sample,PATH,UNDERPASSES,sideCrossing} from './alignment.js';
import {l35TrafficCurve,L35_LINES} from './routes.js';
import {CONTROL_DEFAULTS,configure,createSignal,stepSignal,aspect,tramCommand} from './control-system.js';
import './control-room.css';

const seconds=n=>Math.round(n||0)+' s',kmh=n=>Math.round((n||0)*3.6),q=(root,id)=>root.querySelector('#occ-'+id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createControlRoom(api){
 const {state,renderer,scene}=api,settings={...CONTROL_DEFAULTS};
 // ponytail: three camera feeds at about 5 Hz share one renderer; use render targets if a larger video wall is needed.
 let selected=0,selectedTram=0,lastDraw=-1,lastRender=0,log=[],shiftDone=false,sandbox=false,completedStops=0,delay=0,roadDelay=0,excess=0,served=new Map(),feedFocus='junction',arrivalGap=5;
 const cameras=[new T.PerspectiveCamera(48,1,.5,1100),new T.PerspectiveCamera(48,1,.5,1100),new T.PerspectiveCamera(48,1,.5,1100)];
 const root=document.createElement('main');root.id='control-room';root.dataset.detail='guided';
 const choices=(items,value)=>items.map(([key,label,detail])=>`<button type="button" data-choice="${escape(key)}" aria-pressed="${String(key)===String(value)}"><b>${escape(label)}</b>${detail?`<small>${escape(detail)}</small>`:''}</button>`).join('');
 const bank=(id,label,items,value,tone='blue')=>`<fieldset id="occ-${id}" class="occ-button-bank" data-bank="${id}" data-tone="${tone}"><legend>${label}</legend><div class="occ-bank-buttons">${choices(items,value)}</div></fieldset>`;
 const slider=(key,label,min,max,unit,value)=>`<label class="occ-slider">${label}<output id="occ-${key}-value">${value}${unit}</output><input data-setting="${key}" aria-label="${label}" type="range" min="${min}" max="${max}" step="1" value="${value}"></label>`;
 root.innerHTML=`<header class="occ-top"><a class="occ-brand" href="#" aria-label="Return to game menu">SGMTS <span>OPERATIONS</span></a><div class="occ-location">洪水橋・廈村 <small>Network control centre</small></div><div class="occ-live" id="occ-live">● LIVE SIMULATION</div><time id="occ-clock">08:15:00</time><button class="theme-toggle" type="button" aria-label="Switch interface theme">☾ Dark theme</button><button id="occ-flash" aria-pressed="true">Flashing on</button><button id="occ-pause" data-tone="amber">Pause</button><button id="occ-exit">Exit mode</button></header>
 <div class="occ-toolbar"><div><h1>Keep the city moving.</h1><p>Line 01 <span> / </span> Network overview</p></div><div class="occ-toolbar-controls">${bank('detail','Workspace',[['guided','Guided operator'],['engineering','Signal engineer']],'guided')}${bank('fleet','Service pattern · starts new shift',[['300','6 trams','5-minute headway'],['210','17 trams','3.5-minute headway']],300,'teal')}<button id="occ-help" aria-expanded="false">Operator guide</button></div></div>
 <section class="occ-guide" id="occ-guide" hidden><strong>Your first shift</strong><p>Keep trams moving and road queues below 65 seconds for five simulated minutes. Select a junction on the map to see why it changes. Select a tram to set its speed, hold it, skip a stop, or terminate its service. Requests always pass through the signal clearance sequence. The balance slider gives trams a stronger voice, not an unconditional green.</p><p>Green = proceed, amber = clearing, red = stop. Pedestrians have a separate protected stage. CCTV shows the same live 3D vehicles as the map. Engineering view reveals scores, detector occupancy and all timing parameters. This is a game interpretation, with finite recycled road traffic and terminal-only turnbacks.</p></section>
 <section class="occ-kpis" aria-label="Live network indicators"><div><small>Trams in service</small><strong id="occ-active">6<span> / 6</span></strong></div><div><small>Road vehicles queued</small><strong id="occ-queues">0</strong></div><div><small>Longest road wait</small><strong id="occ-wait">0 <span>s</span></strong></div><div><small>Completed station calls</small><strong id="occ-stops">0</strong></div><div class="occ-shift"><small id="occ-shift-label">Five-minute shift</small><strong id="occ-shift">05:00 <span>remaining</span></strong></div></section>
 <div class="occ-workspace"><section class="occ-map-panel"><div class="occ-panel-title"><h2>Live corridor</h2><span>01 / NETWORK</span></div><div class="occ-map-wrap"><svg id="occ-map" viewBox="0 0 660 600" role="group" aria-label="Live corridor map: select a tram or junction"></svg><div class="occ-map-key"><span class="tram">◆ Tram</span><span class="green">● Proceed</span><span class="red">● Stop</span><span>◎ Station</span><span>╪ Grade separated</span></div></div><div class="occ-map-caption"><span>Geographic alignment · A1 → A7</span><span id="occ-map-caption">Live detector data</span></div>
 <div class="occ-fleet-heading"><h2>Fleet dispatch</h2><span>Select a service to issue an instruction</span></div><div class="occ-fleet-scroll"><table class="occ-fleet-table"><thead><tr><th>Service</th><th>Direction / next</th><th>Speed</th><th>Status</th></tr></thead><tbody id="occ-fleet-body"></tbody></table></div>
 <div class="occ-dispatch"><div><strong id="occ-tram-name">T001</strong><span id="occ-tram-state"></span></div><label>Speed ceiling <output id="occ-speed-value">30 km/h</output><input id="occ-speed" aria-label="Selected tram speed ceiling" type="range" min="0" max="50" value="30"></label>${bank('speed-presets','Quick speed ceiling',[0,10,20,30,40,50].map(n=>[n,n+' km/h']),30,'teal')}${bank('destination','Service destination',[['through','Through service','Both terminals'],['A1','Terminate at A1','Nai Wai'],['A7','Terminate at A7','Industry Park']],'through','teal')}<fieldset class="occ-button-bank" data-tone="amber"><legend>Movement commands</legend><div class="occ-bank-buttons"><button id="occ-hold" aria-pressed="false">Hold tram</button><button id="occ-skip">Skip next stop</button></div></fieldset><p id="occ-command" role="status">Select a tram to control its service.</p></div></section>
 <section class="occ-signal-panel"><div class="occ-panel-title"><h2>Junction control</h2><span>02 / SIGNALS</span></div>${bank('junction','Select junction',[],0,'blue')}<div class="occ-stage" id="occ-stage"></div><div class="occ-aspects" id="occ-aspects"></div><div class="occ-decision"><small>WHY THIS DECISION</small><p id="occ-reason"></p></div><div class="occ-queue-detail" id="occ-queue-detail"></div><div class="occ-sequence" id="occ-sequence"></div>
 <div class="occ-section-title"><h3>Traffic balance</h3><span>NETWORK POLICY</span></div><div class="occ-presets" role="group" aria-label="Traffic balance presets"><button data-tone="blue" data-preset="0" aria-pressed="false">Road relief</button><button data-tone="teal" data-preset="2" aria-pressed="true">Balanced</button><button data-tone="amber" data-preset="4" aria-pressed="false">Tram recovery</button></div>${slider('priority','Tram priority weight',0,5,'×',2)}${slider('extension','Maximum green extension',0,20,' s',10)}<p class="occ-hint">Road queues and pedestrians can override a tram request. A blocked exit keeps trams at red.</p>
 <div class="occ-engineering"><h3>Controller parameters</h3>${slider('minGreen','Minimum green',8,25,' s',12)}${slider('maxGreen','Base maximum green',25,60,' s',35)}${slider('maxWait','Starvation threshold',40,120,' s',65)}${slider('amber','Amber interval',3,6,' s',3)}${slider('allRed','All-red intergreen',3,10,' s',3)}${slider('pedWalk','Pedestrian invitation',7,15,' s',7)}<label class="occ-slider">Road re-entry spacing <output id="occ-arrival-value">5 s</output><input id="occ-arrival" type="range" min="0" max="20" value="5" aria-label="Road traffic re-entry spacing"></label><div id="occ-scores" class="occ-scores"></div><details><summary>Read the decision logic</summary><p>Tram pressure = Σ priority × (1 + passengers / 60 + capped stopped time / 30) / (1 + arrival time / 25) + red wait / 12. Road pressure = queued vehicles + longest wait / 12. Pedestrian pressure = waiting people × 1.5 + red wait / 10.</p><p>After minimum green, serve higher pressure, an operator request, or an overdue movement. End at maximum green (plus bounded tram extension). Oldest overdue movement wins. Amber → all-red → empty conflict area → next stage. Walk invitation → pedestrian clearance → all-red. These are game rules, not SCOOT, SCATS, ETCS, or a certified safety system.</p></details></div>
 <fieldset class="occ-button-bank"><legend>Request next stage</legend><div class="occ-bank-buttons"><button data-tone="teal" data-request="tram" aria-pressed="false"><b>Trams</b><small>Request</small></button><button data-tone="blue" data-request="road" aria-pressed="false"><b>Road traffic</b><small>Request</small></button><button data-tone="violet" data-request="ped" aria-pressed="false"><b>Pedestrians</b><small>Request</small></button></div></fieldset><p class="occ-hint">Requests wait for minimum green and clearance. Overdue demand goes first.</p><fieldset class="occ-button-bank" data-tone="red"><legend>Protection & fault testing</legend><div class="occ-bank-buttons"><button id="occ-isolate" aria-pressed="false">Isolate junction</button><button id="occ-fault" class="occ-engineering" aria-pressed="false">Simulate detector fault</button></div></fieldset><p id="occ-signal-message" role="status"></p></section>
 <aside class="occ-surveillance"><div class="occ-panel-title"><h2>Live surveillance</h2><span>03 / CCTV</span></div><div class="occ-camera-picker">${bank('feed','Primary CCTV camera',[['junction','Junction','Selected junction'],['tram','Track tram','Selected service'],...STOPS.map(st=>[st.id,st.id,st.name])],'junction','violet')}</div><div class="occ-feeds">${[0,1,2].map((n)=>`<figure class="occ-feed"><div class="occ-feed-view" data-feed="${n}"></div><figcaption><b id="occ-feed-name-${n}">CAM 0${n+1}</b><span class="occ-feed-time">LIVE</span></figcaption></figure>`).join('')}</div><p class="occ-hint">Live views of the game world · select junctions and trams to inspect them.</p><div class="occ-panel-title occ-log-title"><h2>Operations log</h2><button id="occ-download">Export</button></div><ol id="occ-log" aria-label="Recent operations events"></ol><div id="occ-result" hidden><h3>Shift complete</h3><p id="occ-result-text"></p><button id="occ-continue">Continue in sandbox</button><button id="occ-restart">New shift</button></div></aside></div><footer class="occ-footer"><span>SIMULATION / LOCAL CONTROL <span id="occ-health"></span></span><span>Signal decisions and vehicle movements share one simulation clock.</span></footer>`;
 document.body.append(root);
 let pointerDown=false;root.addEventListener('pointerdown',()=>pointerDown=true);addEventListener('pointerup',()=>pointerDown=false);addEventListener('pointercancel',()=>pointerDown=false);
 const el=id=>q(root,id),fleet=()=>api.getFleet(),signals=()=>api.getSignals(),current=()=>signals()[selected],tram=()=>fleet()[selectedTram];
 const selectBank=(id,value)=>{for(const b of el(id).querySelectorAll('[data-choice]'))b.setAttribute('aria-pressed',b.dataset.choice===String(value));};
 const addLog=message=>{log.unshift({time:state.time,message});if(log.length>200)log.pop();};
 const command=(kind,value)=>{const a=tram();const message=tramCommand(a,kind,value,STOPS);el('command').textContent=message;addLog(`${a?.control?.id||'Fleet'} · ${message}`);syncTram();};
 function syncTram(){const a=tram();if(!a?.control)return;el('speed').value=a.control.speed;el('speed-value').value=a.control.speed+' km/h';selectBank('destination',a.control.destination);selectBank('speed-presets',a.control.speed);el('hold').textContent=a.control.hold?'Release hold':'Hold tram';el('hold').setAttribute('aria-pressed',a.control.hold);}
 function chooseTram(index){selectedTram=index;syncTram();lastDraw=-1;}
 function chooseSignal(index){selected=index;selectBank('junction',index);lastDraw=-1;}
 el('pause').onclick=api.pause;el('exit').onclick=api.exit;root.querySelector('a').onclick=e=>{e.preventDefault();api.exit();};
 root.dataset.flash='true';el('flash').onclick=()=>{const on=root.dataset.flash!=='true';root.dataset.flash=String(on);el('flash').setAttribute('aria-pressed',on);el('flash').textContent=on?'Flashing on':'Flashing off';};
 const selections={detail:value=>root.dataset.detail=value,fleet:value=>{api.setHeadway(Number(value));api.restart();},junction:value=>chooseSignal(Number(value)),feed:value=>feedFocus=value,destination:value=>command('destination',value),'speed-presets':value=>command('speed',value)};
 root.addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(!b)return;const id=b.closest('[data-bank]').dataset.bank;if(id==='fleet'&&b.getAttribute('aria-pressed')==='true')return;selections[id](b.dataset.choice);selectBank(id,b.dataset.choice);lastDraw=-1;draw();});
 el('help').onclick=()=>{el('guide').hidden=!el('guide').hidden;el('help').setAttribute('aria-expanded',!el('guide').hidden);};
 el('speed').oninput=e=>command('speed',e.target.value);el('hold').onclick=()=>command('hold');el('skip').onclick=()=>command('skip');
 for(const input of root.querySelectorAll('[data-setting]'))input.oninput=e=>{const key=e.target.dataset.setting;if(configure(settings,key,e.target.value)){el(key+'-value').value=settings[key]+(key==='priority'?'×':' s');addLog('Network policy · '+key+' = '+settings[key]);}else e.target.value=settings[key];for(const b of root.querySelectorAll('[data-preset]'))b.setAttribute('aria-pressed',Number(b.dataset.preset)===settings.priority);};
 for(const button of root.querySelectorAll('[data-preset]'))button.onclick=()=>{const input=root.querySelector('[data-setting="priority"]');input.value=button.dataset.preset;input.dispatchEvent(new Event('input'));};
 el('arrival').oninput=e=>{arrivalGap=Number(e.target.value);el('arrival-value').value=arrivalGap+' s';};
 for(const b of root.querySelectorAll('[data-request]'))b.onclick=()=>{current().control.request=b.dataset.request;const message='Queued '+b.dataset.request+' stage; clearance and overdue demand remain protected.';el('signal-message').textContent=message;addLog(current().name+' · '+message);};
 el('isolate').onclick=()=>{const s=current().control;s.isolated=!s.isolated;addLog(current().name+' · '+(s.isolated?'Isolation requested; clearing movements before all-red.':'Automatic control restored.'));};
 el('fault').onclick=()=>{const s=current().control;s.fault=!s.fault;addLog(current().name+' · '+(s.fault?'Detector fault injected; fail to all-red.':'Detector restored.'));};
 el('continue').onclick=()=>{sandbox=true;shiftDone=false;el('result').hidden=true;api.pause();addLog('Five-minute shift complete; continuing sandbox.');};
 el('restart').onclick=()=>api.restart();
 el('download').onclick=()=>{const blob=new Blob([JSON.stringify({settings,time:state.time,completedStops,roadDelay,tramDelay:delay,events:log},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sgmts-operations-log.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function initializeFleet(){fleet().forEach((a,i)=>{a.control={id:'T'+String(i+1).padStart(3,'0'),speed:30,hold:false,destination:'through',terminated:false,skipped:[],wait:0};served.set(a,0);});selectedTram=Math.max(0,fleet().findIndex(a=>a.active));syncTram();}
 function reset(){Object.assign(settings,CONTROL_DEFAULTS);log=[];served=new Map();completedStops=delay=roadDelay=excess=0;shiftDone=sandbox=false;selected=0;feedFocus='junction';arrivalGap=5;lastDraw=-1;el('result').hidden=true;selectBank('feed','junction');el('arrival').value=5;el('arrival-value').value='5 s';selectBank('fleet',state.headway);
  for(const [key,value] of Object.entries(settings)){root.querySelector(`[data-setting="${key}"]`).value=value;el(key+'-value').value=value+(key==='priority'?'×':' s');}
  for(const b of root.querySelectorAll('[data-preset]'))b.setAttribute('aria-pressed',b.dataset.preset==='2');
  signals().forEach(s=>s.control=createSignal(s.c));api.getTraffic().forEach(c=>{c.queueWait=0;c.releaseAt=0;c.wasQueued=false;});initializeFleet();
  el('junction').querySelector('.occ-bank-buttons').innerHTML=choices(signals().map((s,i)=>[i,'J'+String(i+1).padStart(2,'0'),s.name]),0);addLog('Control desk online. Five-minute shift started; balanced priority enabled.');buildMap();draw();
 }
 function inTramBox(a,s){const d=(a.s-s.centre)*a.dir;return a.active&&d>-(s.stop+6)+.1&&d<s.stop+32;}
 function tick(dt){
  if(shiftDone)return;
  for(const a of fleet().filter(a=>a.active)){a.control.skipped=a.control.skipped.filter(id=>(a.s-STOPS.find(st=>st.id===id).s)*a.dir<160);a.control.wait=a.v<.2&&!a.dwell?a.control.wait+dt:0;delay+=a.v<.2&&!a.dwell?dt:0;const count=a.served.length,previous=served.get(a)||0;if(count>previous)completedStops+=count-previous;served.set(a,count);}
  for(const c of api.getTraffic()){
   const line=c.curve?(c.curve===l35TrafficCurve?L35_LINES.d6Out:L35_LINES.d6Return):null;
   const upstream=c.curve?c.routeDistance+c.length/2<=line+.3:c.lat*c.dir<-(sideCrossing(c.junction,c.dir)+3+c.length/2)+.5;
   if(c.releaseAt||!upstream){c.queueWait=0;c.wasQueued=false;}else if(c.v<.3||c.wasQueued){c.queueWait+=dt;c.wasQueued=c.queueWait>=1;}else c.queueWait=0;
  }
  for(const sig of signals()){
   const s=sig.control,normal=api.getTraffic().filter(c=>c.junction?.c===sig.c),turning=sig.c===2650?api.getTraffic().filter(c=>c.curve):[];
   const queued=normal.filter(c=>c.lat*c.dir<0&&c.wasQueued&&!c.releaseAt),turnQueue=turning.filter(c=>{const line=c.curve===l35TrafficCurve?L35_LINES.d6Out:L35_LINES.d6Return;return c.routeDistance+c.length/2<=line+.3&&line-c.routeDistance<100&&c.wasQueued;});
   const allQueue=[...queued,...turnQueue],trams=fleet().filter(a=>a.active&&!a.terminal&&(sig.centre-a.s)*a.dir>sig.stop+5&&(sig.centre-a.s)*a.dir<200).map(a=>({eta:Math.max(0,Math.abs(sig.centre-a.s)-sig.stop)/Math.max(a.v,2),wait:a.control.wait,pax:a.pax}));
   const peds=api.getCrossers().filter(p=>p.signal===sig.c),r=sample(sig.centre);
   const input={trams,queue:allQueue.length,roadWait:Math.max(0,...allQueue.map(c=>c.queueWait)),pedWaiting:peds.filter(p=>!p.active&&p.wait<=0).length,pedOccupied:peds.some(p=>p.active),tramOccupied:fleet().some(a=>inTramBox(a,sig)),
    roadOccupied:normal.some(c=>c.lat*c.dir>-(sideCrossing(sig,c.dir)+3+c.length/2)+.1&&c.lat*c.dir<sideCrossing(sig,-c.dir)+3+c.length/2)||turning.some(c=>{const p=c.group.position,dx=p.x-r.x,dz=p.z-r.z;return Math.abs(dx*r.lx+dz*r.lz)<sideCrossing(sig,-1)+2&&Math.abs(dx*r.tx+dz*r.tz)<sig.stop+c.length/2-1;}),
    blockedExit:fleet().some(a=>a.active&&a.v<.3&&(a.s-sig.centre)*a.dir>sig.stop+6&&(a.s-sig.centre)*a.dir<sig.stop+72),
    directions:[-1,1].map(dir=>{const list=queued.filter(c=>c.dir===dir);return {dir,count:list.length,metres:list.length?Math.max(...list.map(c=>Math.abs(c.lat)+c.length/2))-sideCrossing(sig,dir)-3:0,wait:Math.max(0,...list.map(c=>c.queueWait))};}),turnQueue:turnQueue.length};
   roadDelay+=allQueue.length*dt;excess+=allQueue.filter(c=>c.queueWait>65).length*dt;const before=s.stage;stepSignal(s,dt,input,settings);if(s.stage!==before)addLog(sig.name+' · '+s.stage+' · '+s.reason);
  }
  if(state.time>=300&&!sandbox){if(state.screen==='driving')api.pause();shiftDone=true;el('result').hidden=false;el('result-text').textContent=`${completedStops} station calls · ${Math.round(roadDelay)} vehicle-seconds of road delay · ${Math.round(delay)} tram-seconds stopped. Balance score ${Math.max(0,Math.round(100-excess/15))}/100. ${excess>0?'Some road users exceeded the 65-second objective.':'Road queues stayed within the 65-second objective.'}`;addLog('Five-minute shift completed.');}
 }
 const xs=PATH.map(p=>p.x),zs=PATH.map(p=>p.z),minX=Math.min(...xs),minZ=Math.min(...zs),maxX=Math.max(...xs),maxZ=Math.max(...zs),scale=Math.min(360/(maxX-minX),500/(maxZ-minZ));
 const map=p=>({x:220+(p.x-(minX+maxX)/2)*scale,y:50+(p.z-minZ)*scale});
 function buildMap(){const path=PATH.filter((_,i)=>i%10===0).map((p,i)=>{const a=map(p);return `${i?'L':'M'}${a.x.toFixed(1)},${a.y.toFixed(1)}`;}).join(' ');
  el('map').innerHTML=`<defs><pattern id="occ-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#253139" stroke-width=".6"/></pattern></defs><rect width="660" height="600" fill="url(#occ-grid)"/><text x="605" y="40" class="occ-north">N ↑</text><path d="${path}" stroke="#38515a" stroke-width="13" fill="none"/><path d="${path}" stroke="#7faaa5" stroke-width="3" fill="none"/>${UNDERPASSES.map(j=>{const a=map(sample(j.s));return `<path d="M${a.x-25} ${a.y-6}h50m-50 12h50" stroke="#66737d" stroke-width="2"/><text x="${a.x+32}" y="${a.y+4}" class="occ-map-small">${j.name} · underpass</text>`;}).join('')}${STOPS.map((st,i)=>{const p=map(sample(st.s));return `<circle cx="${p.x}" cy="${p.y}" r="6" fill="#121e25" stroke="#b8c8c8" stroke-width="2"/><text x="${p.x+(i%2?16:-16)}" y="${p.y-10}" text-anchor="${i%2?'start':'end'}" class="occ-stop-label">${st.id} ${escape(st.name)}</text>`;}).join('')}<g id="occ-map-signals"></g><g id="occ-map-trams"></g>`;
 }
 function draw(){if(state.mode!=='control'||pointerDown)return;const focused=document.activeElement,focusTram=focused?.dataset.tram,focusSignal=focused?.dataset.signal,focusTable=!!focused?.closest('.occ-fleet-table');if(state.time-lastDraw<.25&&lastDraw>=0&&state.screen==='driving')return;lastDraw=state.time;
  const active=fleet().filter(a=>a.active),sig=current(),s=sig?.control;if(!s)return;
  el('pause').textContent=state.screen==='paused'?'Resume':'Pause';el('pause').classList.toggle('occ-pulse',state.screen==='paused'&&!shiftDone);el('pause').setAttribute('aria-pressed',state.screen==='paused');el('live').textContent=state.screen==='paused'?'Ⅱ SIMULATION PAUSED':'● LIVE SIMULATION';el('clock').textContent=api.clockText(state.time);el('active').innerHTML=active.length+'<span> running</span>';
  const queue=signals().reduce((n,j)=>n+j.control.input.queue,0),wait=Math.max(0,...signals().map(j=>j.control.input.roadWait));el('queues').textContent=queue;el('wait').innerHTML=Math.round(wait)+' <span>s</span>';el('wait').classList.toggle('occ-warning',wait>65);el('wait').classList.toggle('occ-pulse',wait>65);el('stops').textContent=completedStops;
  const left=Math.max(0,Math.ceil(300-state.time));el('shift').innerHTML=sandbox?'OPEN <span>sandbox</span>':`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')} <span>remaining</span>`;
  el('health').textContent=signals().some(j=>j.control.fault||j.control.isolated)?' / INTERVENTION ACTIVE':' / ALL CONTROLLERS ONLINE';
  el('stage').innerHTML=`<strong>${{tram:'Tram movement',road:'Road movement',ped:'Pedestrian crossing',pedClear:'Pedestrian clearance',tramAmber:'Tram amber',roadAmber:'Road amber',clear:'All-red clearance'}[s.stage]}</strong><span>${seconds(s.age)} elapsed</span>`;
  el('aspects').innerHTML=['tram','road','ped'].map(axis=>`<div><i class="${aspect(s,axis)}"></i><strong>${axis==='ped'?'Walk':axis==='road'?'Road':'Tram'}</strong><span>${{go:'PROCEED',stop:'STOP',amber:'CLEAR'}[aspect(s,axis)]}</span></div>`).join('');el('reason').textContent=s.reason;
  el('queue-detail').innerHTML=`<div><small>Tram requests</small><b>${s.input.trams.length}</b></div><div><small>Pedestrians waiting</small><b>${s.input.pedWaiting||0}</b></div>${(s.input.directions||[]).map(d=>`<div><small>${d.dir===1?'West':'East'} approach</small><b>${d.count} veh · ${Math.max(0,Math.round(d.metres))} m</b><span>${seconds(d.wait)} longest wait</span></div>`).join('')}<p>L35 turning queue: ${s.input.turnQueue||0} vehicles</p>`;
  el('sequence').innerHTML=['tram','tramAmber','clear','road','roadAmber','ped','pedClear'].map(k=>`<span class="${s.stage===k?'active':''}">${{tram:'Tram',tramAmber:'Amber',clear:'All red',road:'Road',roadAmber:'Amber',ped:'Walk',pedClear:'Clear'}[k]}</span>`).join('');
  el('scores').innerHTML=`<b>Live pressure / red wait</b>${Object.entries(s.scores).map(([k,v])=>`<span>${k}: ${v.toFixed(1)} / ${seconds(s.wait[k])}</span>`).join('')}<span>Conflict area: ${s.input.tramOccupied||s.input.roadOccupied||s.input.pedOccupied?'OCCUPIED':'CLEAR'}</span><span>Tram exit: ${s.input.blockedExit?'BLOCKED':'AVAILABLE'}</span><span>Next request: ${s.request||'automatic'}</span>`;
  el('isolate').textContent=s.isolated?'Restore automatic':'Isolate junction';el('fault').textContent=s.fault?'Restore detector':'Simulate detector fault';
  for(const [id,on] of [['isolate',s.isolated],['fault',s.fault]]){el(id).setAttribute('aria-pressed',on);el(id).classList.toggle('occ-pulse',on);}
  for(const b of root.querySelectorAll('[data-request]')){const pending=s.request===b.dataset.request;b.setAttribute('aria-pressed',pending);b.classList.toggle('occ-pulse',pending);b.querySelector('small').textContent=pending?'Request pending':s.stage===b.dataset.request?'Stage active':'Request';}
  for(const b of el('junction').querySelectorAll('[data-choice]')){const c=signals()[Number(b.dataset.choice)].control;b.classList.toggle('occ-pulse',c.fault||c.isolated);b.dataset.alarm=String(c.fault||c.isolated);b.title=c.fault?'Detector fault':c.isolated?'Junction isolated':'Automatic control';}
  el('fleet-body').innerHTML=fleet().map((a,i)=>a.active?`<tr class="${i===selectedTram?'selected':''}"><td><button data-tram="${i}">${a.control.id}</button></td><td>${a.dir===1?'↑ A7':'↓ A1'} / ${STOPS[a.stopIndex]?.id||'Turnback'}</td><td>${kmh(a.v)} <small>km/h</small></td><td>${a.control.terminated?'Terminated':a.control.hold?'Held':a.terminal?'Turning':a.dwell?'Boarding':a.v<.2?'Waiting':'Running'}</td></tr>`:'').join('');
  for(const b of el('fleet-body').querySelectorAll('[data-tram]'))b.onclick=()=>chooseTram(Number(b.dataset.tram));
  const a=tram();el('tram-name').textContent=a.control.id;el('tram-state').textContent=`${a.pax||0} passengers · ${a.dir===1?'Northbound':'Southbound'}`;
  el('map-signals').innerHTML=signals().map((j,i)=>{const p=map(sample(j.centre)),c=j.control;return `<g role="button" tabindex="0" data-signal="${i}" aria-label="${escape(j.name)}, tram ${aspect(c)}, ${c.input.queue} road vehicles queued" class="occ-map-select ${selected===i?'selected':''}"><path d="M${p.x-24} ${p.y}H${p.x+160}" stroke="#536571" stroke-width="3"/><rect x="${p.x+25}" y="${p.y-23}" width="200" height="47" rx="3"/><circle cx="${p.x+39}" cy="${p.y-7}" r="4" class="${aspect(c)}"/><text x="${p.x+51}" y="${p.y-3}">J0${i+1} · ${escape(j.name)}</text><text x="${p.x+38}" y="${p.y+14}" class="occ-map-small">${c.input.queue} veh / ${Math.round((c.input.directions||[]).reduce((v,d)=>v+Math.max(0,d.metres),0))} m · ${seconds(c.input.roadWait)} · ${aspect(c)==='go'?'GO':aspect(c).toUpperCase()}</text></g>`;}).join('');
  el('map-trams').innerHTML=fleet().map((a,i)=>{if(!a.active)return '';const p=map(a.sections[0].position),x=p.x+(a.dir===1?-12:12);return `<g role="button" tabindex="0" data-tram="${i}" aria-label="${a.control.id}, ${kmh(a.v)} kilometres per hour" class="occ-tram-marker ${selectedTram===i?'selected':''}"><path d="M${x} ${p.y-a.dir*8}l-6 ${a.dir*14}h12Z"/><text x="${x+(a.dir===1?-10:10)}" y="${p.y+4}" text-anchor="${a.dir===1?'end':'start'}">${a.control.id}</text></g>`;}).join('');
  for(const b of el('map').querySelectorAll('[data-signal],[data-tram]')){const select=()=>b.dataset.signal!==undefined?chooseSignal(Number(b.dataset.signal)):chooseTram(Number(b.dataset.tram));b.onclick=select;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};}
  if(focusTram!==undefined)(focusTable?el('fleet-body'):el('map')).querySelector(`[data-tram="${focusTram}"]`)?.focus({preventScroll:true});if(focusSignal!==undefined)el('map').querySelector(`[data-signal="${focusSignal}"]`)?.focus({preventScroll:true});
  el('log').innerHTML=log.slice(0,9).map(e=>`<li><time>${api.clockText(e.time)}</time><span>${escape(e.message)}</span></li>`).join('');
 }
 function render(now){
  if(now-lastRender<180)return;lastRender=now;
  const primary=feedFocus==='tram'?tram().s:feedFocus==='junction'?current().centre:STOPS.find(s=>s.id===feedFocus).s;
  const views=[{s:primary,label:feedFocus==='tram'?tram().control.id:feedFocus==='junction'?current().name:feedFocus},{s:tram().s,label:tram().control.id+' / tracking'},{s:signals()[(selected+1)%signals().length].centre,label:signals()[(selected+1)%signals().length].name}];
  renderer.setRenderTarget(null);renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);renderer.clear();renderer.setScissorTest(true);
  const oldShadow=renderer.shadowMap.enabled;renderer.shadowMap.enabled=false;
  for(let i=0;i<views.length;i++){const box=root.querySelector(`[data-feed="${i}"]`).getBoundingClientRect();if(box.bottom<0||box.top>innerHeight||box.width<1)continue;const v=views[i],r=sample(v.s),c=cameras[i];api.prepareView(v.s);c.aspect=box.width/box.height;c.position.set(r.x+r.lx*30-r.tx*30,r.y+24,r.z+r.lz*30-r.tz*30);c.lookAt(r.x,r.y+1,r.z);c.updateProjectionMatrix();renderer.setViewport(box.left,innerHeight-box.bottom,box.width,box.height);renderer.setScissor(box.left,innerHeight-box.bottom,box.width,box.height);renderer.render(scene,c);el('feed-name-'+i).textContent=`CAM 0${i+1} / ${v.label}`;}
  renderer.shadowMap.enabled=oldShadow;renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);root.querySelectorAll('.occ-feed-time').forEach(e=>e.textContent=(state.screen==='paused'?'PAUSED · ':'LIVE · ')+api.clockText(state.time));
 }
 return {reset,tick,draw,render,settings,get finished(){return shiftDone;},get arrivalGap(){return arrivalGap;},get selectedS(){return current()?.centre||STOPS[0].s;},inTramBox,get log(){return log;}};
}
